### PR TITLE
Multibrand support

### PR DESCRIPTION
**Pull request by jpalmieri**
Zendesk introduced [multibrand](https://support.zendesk.com/hc/en-us/articles/204280606-Introducing-Zendesk-Multibrand) a while back, and we just started using it to have more sandbox help centers to use for testing. This work will allow users to add multiple brands to their config file, and call the specific brand in their scripts.

@victormach I'd love to head your thoughts on this, if any. However, I'll totally understand if you don't have the time.

### CODE REVIEW

**Comment by PolRod** [comment]
Awesome! When only having one brand, it would be cool to not to have to specify it. I can't tell if this is already enabled.

**Comment by victormach** [comment]
@jpalmieri Looks great! I think my only question is why use an external lib (Hashie)? I think the standard Ruby yaml library has a to_hash method to parse the file. That's really the only nitpick I have and I might just be totally overlooking something!

**Comment by jpalmieri** [comment]
@PolRod That's a good idea. I didn't code it that way, but maybe I should. You may want to take a look at the updated readme for more info on how to use it. I made it so that you supply the brand as a second argument when initializing an instance of the wrapper, e.g., `stakeholder_sandbox = ZDHttpApi.new(:sandbox, :stakeholders)`

I was thinking more about that and I kind of don't like the fact that we (And anyone else potentially using this) will have to modify our scripts after this upgrade). Maybe the brand to be used should be specified in the config file? But that seems like it would also be inconvenient. Maybe there should be some sort of controller or something that initializes all of your brands, and which could have some `method_missng` magic in it that calls the brand when someone calls  it in a script (I'm looking at you, @victormach).

@victormach I wanted to make the config file a `.yaml` file, but yaml imports keys as strings rather than symbols, and doesn't have any out-of-the-box ways of importing them as symbols instead, or of converting them after imported. Yaml actually loads the file as a hash already; I'm using `Hashie.symbolize_keys` on the hash loaded from the config file to convert the string keys to symbols. Strangely, the ruby standard lib doesn't have any way of doing this (although Rails does). I could have written a custom method (read this statement as: _I could have copied one from SO_), but this just seemed like an easy way to keep the code clean.

However, I'm open to suggestions. I highly respect both of your opinions!

**Comment by jpalmieri** [comment]
@PolRod I made an addition that will use the first brand in the yaml file if no brand is specified https://github.com/jpalmieri/zd_wrapper/commit/b6881e80e2d2c9529d3d9d61d6839b8144453df9

**Pull request closed without merging**
